apiVersion: batch/v1
kind: Job
metadata:
   name: job-pi
spec:
   template:
      spec:
         containers:
         - name: job-container
           image: perl
           command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
         restartPolicy: Never
   backoffLimit: 4  #If the pod failed to run, it retries for 4 times. after that the Job will be terminated
